services:
  db:
    container_name: 'db'
    image: mysql
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'twitter'
      # MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "pass"
      # MYSQL_ROOT_PASSWORD: "rootpassword"
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3307:3306"
  redis:
    container_name: 'redis'
    image: redis:7
    ports:
      - '6378:6378'
    volumes:
      - './redisdata:/data'
  web:
    build: .
    command: ["manage.py", "runserver", "0.0.0.0:8001"]
    # image: backend
    volumes:
      - ".:/app"
    ports:
      - "8001:8001"
    depends_on:
      - db
      - redis
