# Generated by Django 4.2.2 on 2023-08-18 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followers',
            old_name='following',
            new_name='from_user_id',
        ),
        migrations.RenameField(
            model_name='followers',
            old_name='follower',
            new_name='to_user_id',
        ),
        migrations.AlterUniqueTogether(
            name='followers',
            unique_together={('from_user_id', 'to_user_id')},
        ),
    ]
