# Generated by Django 4.2.2 on 2023-09-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetcomment',
            name='edit',
            field=models.BooleanField(default=False),
        ),
    ]
