# Generated by Django 4.2.2 on 2023-09-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_tweetcomment_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='edit',
            field=models.BooleanField(default=False),
        ),
    ]
