# Generated by Django 4.2.2 on 2023-09-05 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_conversation_message_conversation_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='text',
        ),
    ]
