# Generated by Django 4.2.2 on 2023-09-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_customuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
