# Generated by Django 4.2.2 on 2023-09-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_tweets_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='messages/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='defaultProfile.jpg', upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tweets/'),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='text',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
