# Generated by Django 4.2.2 on 2023-09-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_message_image_alter_customuser_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetcomment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comments/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='defaultProfile.jpg', null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
