# Generated by Django 4.2.2 on 2023-09-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_tweetcomment_image_alter_customuser_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetcomment',
            name='text',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
