# Generated by Django 4.2.2 on 2023-09-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_customuser_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
